# Generated by Django 4.2.30 on 2026-04-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
