# Generated by Django 5.1.2 on 2026-04-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_enrollment_payment_receipt_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_number',
            field=models.CharField(blank=True, help_text='رقم فودافون كاش أو المحفظة الإلكترونية (للمدرسين)', max_length=20, null=True),
        ),
    ]
