# Generated by Django 5.1.2 on 2026-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_materialview_exam_question_examattempt_studentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='مدة الامتحان بالدقائق'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pass_score',
            field=models.PositiveIntegerField(default=50, help_text='درجة النجاح من 100'),
        ),
    ]
